[package]
name = "deadpool-postgres"
version = "0.5.4"
authors = ["Michael P. Jung <michael.jung@terreon.de>"]
description = "Dead simple async pool for tokio-postgres"
keywords = ["async", "database", "pool", "postgres"]
license = "MIT/Apache-2.0"
repository = "https://github.com/bikeshedder/deadpool"
readme = "README.md"
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[dependencies]
deadpool = { path = "../", version = "0.5.0", default-features = false, features = ["managed"] }
async-trait = "0.1.17"
futures = "0.3.1"
log = "0.4"
tokio = { version = "0.2.9", features = ["sync"] }
tokio-postgres = "0.5.1"
# only required when using the config feature
config-crate = { package = "config", version = "0.10.1", default-features = false, optional = true }
serde = { version = "1.0", features = ["derive"], optional = true}
crossbeam = "0.7.3"

[dev-dependencies]
tokio = { version = "0.2.9", features = ["sync", "macros"] }
criterion = { version = "0.3.1" }

[features]
default = ["config"]
config = ["config-crate", "serde", "deadpool/config"]

[[bench]]
name = "readonly"
harness = false
